[package]
name = "rtw"
version = "0.1.0"
edition = "2024"

[lib]
name = "rtw"
path = "src/lib.rs"

[[bin]]
name = "rtw"
path = "src/main.rs"

[dependencies]
glam = "0.30.8"
indicatif = "0.17"
itertools = "0.14.0"
rand = "0.9.2"
